name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: pre-27

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Init with Gradle
        run: gradle init
      - name: Build with Gradle
        working-directory: ./server

        run: gradle build
      - name: Make zip file
        run: zip -r ./stackoverflow-clone.zip .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./stackoverflow-clone.zip s3://$S3_BUCKET_NAME/stackoverflow-clone.zip
      - name: Code Deploy
        run: >
          aws deploy create-deployment --application-name stackoverflow-clone
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name stackoverflow-clone-group
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=stackoverflow-clone.zip